"""Init

Revision ID: e2d689e5e01e
Revises: 9fdb02d62733
Create Date: 2023-05-10 20:10:57.262279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2d689e5e01e'
down_revision = '9fdb02d62733'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
